# render.yaml

services:
  - type: web
    name: fakturomat
    env: python
    python:
      version: "3.10"
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn project1.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: DJANGO_SETTINGS_MODULE
        value: project1.settings
      - key: DJANGO_DEBUG
        value: "False"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DISABLE_COLLECTSTATIC
        value: "0"
    plan: free
    numInstances: 1
    healthCheckPath: /
