# Generated by Django 5.2 on 2025-07-03 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_alter_invoiceitem_options_invoice_tax_breakdown_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='tax_rate',
        ),
    ]
