# Generated by Django 5.2.4 on 2025-07-06 18:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_remove_invoice_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), editable=False, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='VAT rate (%)'),
        ),
    ]
