# Generated by Django 5.2 on 2025-07-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Account Number'),
        ),
        migrations.AddField(
            model_name='client',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='client',
            name='bic_swift',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='BIC/SWIFT'),
        ),
        migrations.AddField(
            model_name='client',
            name='iban',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IBAN'),
        ),
    ]
