# Generated by Django 5.2 on 2025-07-03 09:18

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_account_number_client_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='country',
            field=django_countries.fields.CountryField(default='SI', max_length=2),
        ),
    ]
