# Generated by Django 5.2 on 2025-07-03 09:20

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='country',
            field=django_countries.fields.CountryField(default='SK', max_length=2),
        ),
    ]
