# Generated by Django 5.2 on 2025-07-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='bank_account',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bank Account (IBAN)'),
        ),
    ]
